### ISSUE TITLE
Suggestion for Minecraftify!

### ISSUE THREAD

**Issue by Noodlesy** [Alphalaneous/Projected-Stars#4]
Now, i know this isn't for this mod, but, can you make the singleplayer menu in Minecraftify
![suggestion](https://github.com/user-attachments/assets/e9e9841d-7eac-4590-b2ff-6b389b090aa7)
 look something like this?

**Comment by Alphalaneous** [comment]
This is planned. Currently still trying to figure out the curse that is blur

**Comment by Noodlesy** [comment]
Also, can you make the multiplayer menu be the Globed levels page (if the user has globed)
